<template lang="html">
  <div class="home container" style="background: #779FA1;">
    <h1>Course Ratings</h1>
    <select>
      <option>Select A School</option>
      <option>Knox College</option>
    </select>
  </div>
</template>

<script>
export default {
  name: 'home',

  components: {},

  data() {
    return {
    }
  }

}
</script>

<style lang="css">
select {
  background: #faf7f2;
}
</style>
